**PROBLEMA 1 ***** Ejemplo en DS: en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [1]:
import numpy as np
a = 0
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

V = R + gamma*np.matmul(P,V)
V

#for a in range(1,10000000):
#    V = R + gamma*np.matmul(P,V)
#array([678.25  , 668.3195, 675.1805])


array([10.,  2.,  5.])

**PROBLEMA 2
**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicacion de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producira una nueva matriz con el mismo numero de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la funcion "sigmoid"(descrita a continuacion) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamanio pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la funcion sigmoid. El resultado debe ser un tensor con el mismo numero de filas que la matriz X y una sola columna(una prediccion para cada fila de X

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">


In [4]:
#Defining Sigmoid function
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

#Defining Neural Network - ActFunc=Sigmoid
def Sneural_network(x, hl1, ol):
    hlay = np.matmul(x,hl1)
    siglay = sigmoid(hlay)
    return [np.matmul(siglay,ol), sigmoid(np.matmul(siglay,ol))]

#Defining Neural Network - ActFunc=Relu
def Rneural_network(x, hl1, ol):
    hlay = np.matmul(x,hl1)
    siglay = sigmoid(hlay)
    return [np.matmul(siglay,ol), np.maximum(0,np.matmul(siglay,ol))]


#TESTING SNeural_Network with vectors    
H = np.array([[0.712,0.355,0.268],
                 [0.112,0.855,0.468]])
O= np.array([0.116,0.329,0.708])
xx = [1,1]
Sneural_network(xx, H,O)

#TESTING RNeural_Network with vectors 

X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

Rneural_network(X, H,O)

[array([0.85897151, 0.6748703 , 1.14904686, 1.15125178, 1.14187076,
        0.72619803, 1.15019715, 1.153     , 1.1500904 , 1.153     ]),
 array([0.85897151, 0.6748703 , 1.14904686, 1.15125178, 1.14187076,
        0.72619803, 1.15019715, 1.153     , 1.1500904 , 1.153     ])]